### PR TITLE
Get rid of bower

### PR DESCRIPTION
**Pull request by spinningarrow**
It's basically not needed since `npm` can be used everywhere instead.

Btw, there _is_ an npm package for `normalize.css` – I didn't add it because it feels … weird to add CSS dependencies using npm and because normalize is just a single small CSS file, so we can just check it in. @xevenheaven If you don't think it's weird and think that it should go in there, let me know!

I forgot to mention this in the commit message, but I also deleted `divisions.js` since we're not using it any more.

### CODE REVIEW

**Comment by xevenheaven** [comment]
Haha npm for one css file seems... extravagant. Lol. We can just add it
into index. (y) Same thing for colorbrewer then!

**Comment by spinningarrow** [comment]
Haha glad you agree. If the rest is good, I'll merge this in.

Btw, out of curiosity (since I don't know how colorbrewer really works), how much of colorbrewer are we actually using? I remember you once showed me that we're using only one of the array items in it or something.

**Comment by xevenheaven** [comment]
Yeah go ahead and merge! :+1: (I'm totally just whacking and trying to get
the right emoticon since I'm replying via email lol.)

Yeah for colorbrewer we're using only an array for now. Basically it's just
for theming right, so they have a whole list and we're using one option
outta the list (hence the one array). I left the whole file there since at
that point of time I haven't decided what's the color scheme and all that.

**Comment by spinningarrow** [comment]
Cool, sounds good! Haha you got the correct emoji :stuck_out_tongue:

**Pull request merged**
