### PR TITLE
Email notifications

### PR DESCRIPTION
**Pull request by xevenheaven**
Enabled basic email notifications.
- [x] Include smtp password safely
- [x] Format email body (html)

### CODE REVIEW

**Comment by xevenheaven** [comment]
- http://webdesign.tutsplus.com/articles/build-an-html-email-template-from-scratch--webdesign-12770
- https://www.campaignmonitor.com/css/
- https://css-tricks.com/using-css-in-html-emails-the-real-story/

**Comment by xevenheaven** [comment]
We need to check when the kudos get saved to the DB.

**Comment by spinningarrow** [comment]
https://github.com/deployd/dpd-email/issues/16 should hopefully shed some light on this.

**Comment by spinningarrow** [comment]
Technically, this is ready for merging in but let's do it once we remember the password 😝

**Comment by spinningarrow** [comment]
🍾

**Pull request closed without merging**
