### PR TITLE
ES6ification

### LINKED ISSUE #7: ES6ify ALL the things!

### PR DESCRIPTION
**Pull request by spinningarrow**
This will close #7 once it's merged in.

@xevenheaven, I got started by adding Babel's browserify transform; haven't changed any code in any of the files yet and things seem to be working. We can split up the components between us!

### CODE REVIEW

**Comment by spinningarrow** [comment]
Checklist:
- [ ] ~~Upgrade to React v0.0.13 (it supports ES6 classes - might as well use these even though I don't really like them!)~~
- [ ] ~~Use the ES6 module syntax (this is sort of a maybe since the CommonJS syntax seems to serve the purpose well enough)~~
- [x] Use arrow functions wherever required (this is big - we can get rid of the `.bind(this)` littered throughout the React code)
- [x] Use other ES6 features as necessary

**UPDATE**: Removed the first two from this - we can either do these later or not at all.

**Comment by spinningarrow** [comment]
Btw, just for completeness – we could've also used Traceur (via the `es6ify` transform), but Babel comes built-in with JSX support. Plus, I still don't really know how to pronounce Traceur 😜 and it also creates all these ugly `$`-prefixed variable names!

**Comment by xevenheaven** [comment]
So how do you pronounce Babel?? 😂

**Comment by spinningarrow** [comment]
:laughing: :joy:

**Comment by spinningarrow** [comment]
Bay-bel?

**Comment by xevenheaven** [comment]
@spinningarrow, I've pretty much ES6ifyed the files. Run through them yeah! :+1:

**Comment by spinningarrow** [comment]
You're a star. Let me take a look at the code!

PS. I don't approve of the first two commits' messages :stuck_out_tongue_closed_eyes:

**Comment by spinningarrow** [comment]
It looks really good! I'd like to squash the last two commits into the one before them to keep the history clean though - what do you think?
I can do that if you like (gonna rebase this branch onto master anyway to bring it up to date before merging). Thaaaaaanks for doing all the grunt work!

**Comment by spinningarrow** [comment]
PPS. Did you edit the checklist? Or did I? GitHub doesn't show this information _sigh_ Either way, we're not using the ES6 module syntax yet. That will leave the first two points unchecked, which I'm fine with really, as long as you're fine with it too.

**Comment by xevenheaven** [comment]
I checked the checklist (just to see how it works, really - but all I see changed is the checkmark, so nothing interesting there hahahaha.) I unchecked it again based on what you said.

Please go ahead and squash the commits (basically do whatever you want :stuck_out_tongue_closed_eyes:). You're better at git hahaha.

**Comment by spinningarrow** [comment]
Ooh wait, I didn't realise you could directly check off the boxes - I thought it could only be done by going to 'edit' and then adding the x's there!

That's actually a good reason for _you_ to do the squashing then! But okay, I'll do it this time - you can have the next one :P

**Pull request merged**
